### ISSUE TITLE
Huawei S7706 get_config() failed

### ISSUE THREAD

**Issue by lemarakis** [napalm-automation-community/napalm-huawei-vrp#24]
Hello !

I have 2 switches S7706, 
and I'm attempting to perform a get_config() operation using napalm. 

On one of the switches, the process is not completing and results is:

"_Pattern not detected: '<Switch\\-S7706\\-core>' in output.
Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.
You can also look at the Netmiko session_log or debug log for more information._"

I have tried every combination of optional_args (without any success):
global_delay_factor, fast_cli, timeout, conn_timeout, session_timeout.

With cli, using SSH, I don't have any problem.
I also mention that get_facts(), works as expected.

I am using:
Python 3.11.2 
Netmiko 4.2.0
Napalm 4.1.0

The following script also fails:
napalm --vendor huawei_vrp --user username --password secret --optional_args 'port=22, global_delay_factor=2, read_timeout_override=30.0' 10.10.10.10 call get_config

What do you think might be causing this, and what else can I try?

**Comment by codingnetworksb** [comment]
Hi @lemarakis can you share the full configuration of one this switches?

**Comment by codingnetworksb** [comment]
Because i haven't received an answer in 7 month,  i will close this issue.
