### ISSUE TITLE
 raise ConnectionException("Cannot connect to {}".format(self.hostname))

### ISSUE THREAD

**Issue by BrightHammer0** [napalm-automation-community/napalm-huawei-vrp#3]
交换机管理口已经配置了管理ip
[HUAWEI-MEth0/0/1]di th
#
interface MEth0/0/1
 ip address 192.168.1.248 255.255.255.0
#
return

终端报错 
C:\Users\Administrator>ping 192.168.1.248

正在 Ping 192.168.1.248 具有 32 字节的数据:
来自 192.168.1.248 的回复: 字节=32 时间<1ms TTL=255
来自 192.168.1.248 的回复: 字节=32 时间=2ms TTL=255
来自 192.168.1.248 的回复: 字节=32 时间<1ms TTL=255
来自 192.168.1.248 的回复: 字节=32 时间<1ms TTL=255

192.168.1.248 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 2ms，平均 = 0ms

C:\Users\Administrator>python
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> driver = get_network_driver('huawei_vrp')
>>> device = driver(hostname='192.168.1.248', username='admin', password='admin@huawei.com')
>>> device.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\napalm_huawei_vrp\huawei_vrp.py", line 128, in open
    device_type, netmiko_optional_args=self.netmiko_optional_args
  File "C:\Python27\lib\site-packages\napalm\base\base.py", line 99, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 192.168.1.248
>>>
请问大佬是什么问题

**Comment by tkspuk** [comment]
@BrightHammer0 
The driver just support Python3，I see you're using Python2.78, you can try using Python3. 
这个工具仅支持python，我看你在使用python2.78，你可以用python3试一下

**Comment by BrightHammer0** [comment]
大佬你好 我换了python3.6的解释器，还是报错
Traceback (most recent call last):
  File "C:\python36\lib\site-packages\ntc_templates\parse.py", line 5, in <module>
    from textfsm import clitable
  File "C:\python36\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\python36\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\python36\lib\site-packages\textfsm\terminal.py", line 31, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'
谷歌了一下可能问题是在windows环境无法使用termios模块，所以想请问一下是不是此驱动的使用环境不适用于windows

**Comment by tkspuk** [comment]
理论上python是跨平台的，不存在某个操作系统不能用的情况，你可以用一个虚拟环境测试一下

**Comment by BrightHammer0** [comment]
@tkspuk 
但是我换了python3.6.6，安装了napalm-huawei-vrp后运行代码回报如下错误
![image](https://user-images.githubusercontent.com/55442898/81465942-675c9f00-9200-11ea-8b85-673cff3288c5.png)
它告诉我缺少模块

**Comment by BrightHammer0** [comment]
大佬您好，我通过配置交换机ssh已经成功运行了，但是我有个问题。
我想请问一下，napalm-huawei-vrp模块难道只能用于输出交换机信息吗？
比如我想新添加一个配置vlan的方法，思路应该是怎么样的。
期待您的回复！
