### ISSUE TITLE
New Napalm version dropped the module py23compat

### ISSUE THREAD

**Issue by i4networks** [napalm-automation-community/napalm-huawei-vrp#4]
In the new Napalm version py23compat is no longer available.
Crashing the vrp driver.

**Comment by michadom** [comment]
> 
> 
> In the new Napalm version py23compat is no longer available.
> Crashing the vrp driver.

I also had the same issue. In the meanwhile i installed napalm 2.5.0("pip3 install napalm == 2.5.0") and it's working now. It's workaround just in case you want to use and test with napalm-huawei-vrp.

**Comment by tkspuk** [comment]
@michadom @i4networks Since I am testing in napalm==2.4.0, it's worked. It looks like 2.5.0 is ok at same. what version did you have problems?
Could you please send the detail log to my email，locus@byto.top

**Comment by michadom** [comment]
@tkspuk i tested napalm 3.0.1 and had the issue reported by @i4networks.

**Comment by i4networks** [comment]
@tkspuk  napalm 3.0.0

**Comment by tkspuk** [comment]
Since the development is based on napalm2.4.0, but after the  napalm3.0.0, there are some problems. I will urgently release a new version **v0.1.5**, which will limit the napalm dependency between 2.3.0 and 2.5.0 to ensure that fix issue. 

I'll fix this completely in v0.2.0

**Comment by daca42** [comment]
> Since the development is based on napalm2.4.0, but after the napalm3.0.0, there are some problems. I will urgently release a new version **v0.1.5**, which will limit the napalm dependency between 2.3.0 and 2.5.0 to ensure that fix issue.
> 
> I'll fix this completely in v0.2.0
@tkspuk 
Hello! Very interested to know if this will happen of if perhaps this project has been abandoned? I'd love to be able to use this with the latest version of nornir / NAPALM. Thanks!

**Comment by tkspuk** [comment]
@daca42 I'm sorry that I haven't updated it for a long time. I will release new version this week

**Comment by ggiesen** [comment]
I'm also running into this now. Any word on the update?

**Comment by tkspuk** [comment]
1.0.0 has released. issue fixed

**Comment by FlorianHeigl** [comment]
really cool you managed to do that!
I'm gonna try to learn from the changes you made and port forward the onyx driver the same way :-)
