### ISSUE TITLE
Problem with S2700 models

### ISSUE THREAD

**Issue by jcPOLO** [napalm-automation-community/napalm-huawei-vrp#6]
Hello,

I would like to know against what models you are testing the driver. I could help you to test it with S2700, S7700, S7703, NE40E-X8, NE40E-X3.
I did not see this driver before and I developed one that fit my needs. mainly for S2700 to get info needed in netbox.
I tried this one but I could not get the info expected in netbox (get_facts mainly, like uptime, model version or serial number)
are you planning to upgrade to the newest napalm driver model and dependencies?

**Comment by tkspuk** [comment]
@jcPOLO  

The Netbox use get_Environment () to get the relevant environment information.The API hasn't been updated and adapted yet
I used to mainly verify to the S5700 series of devices.
I will be updating the driver to fit NAPALM3.0 next month.

**Comment by tkspuk** [comment]
the driver has release v1.0.0 to support napalm>3.0.0
