### ISSUE TITLE
you don't statement using napalm-ce

### ISSUE THREAD

**Issue by thddaniel** [napalm-automation-community/napalm-huawei-vrp#8]
Hi @tkspuk,

Your code clearly is including [napalm-ce](https://github.com/napalm-automation-community/napalm-ce).
Based on Apache 2.0 License, you are free to use our project, but you should statement clearly in your project(huawei_vrp.py), and README.md, you are developing based on [napalm-ce](https://github.com/napalm-automation-community/napalm-ce).

**Comment by tkspuk** [comment]
will be updated the readme document
